<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

function yakuza_send($data){
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.telegram.org/bot7165314118:AAHdKoOnVtoSd5z_bOhP0XSJJIwkCe4OO8M/sendMessage');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"chat_id\": \"7005236807\", \"text\": \"".$data."\", \"disable_notification\": false}");

$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

}

?>
