<?php

session_start();
/*
$allowed_countries = ['Australia', 'New Zealand']; 
if (!in_array(x_deux_ip(getenv('REMOTE_ADDR')), $allowed_countries)) {
    include './verifen/popular.php';
    exit();
}
*/

function x_deux_isp($ipp){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://pro.ip-api.com/php/'.$ipp.'?key=I8h97HB1QkUVKV0&fields=status,isp,proxy');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


	$headers = array();
	$headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0';
	$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8';
	$headers[] = 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3';
	//$headers[] = 'Accept-Encoding: gzip, deflate, br';
	$headers[] = 'Dnt: 1';
	$headers[] = 'Connection: keep-alive';
	$headers[] = 'Upgrade-Insecure-Requests: 1';
	$headers[] = 'Sec-Fetch-Dest: document';
	$headers[] = 'Sec-Fetch-Mode: navigate';
	$headers[] = 'Sec-Fetch-Site: none';
	$headers[] = 'Sec-Fetch-User: ?1';
	$headers[] = 'Pragma: no-cache';
	$headers[] = 'Cache-Control: no-cache';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);


	$expp3  = explode(':"isp";', $result);
	$expp33 = explode(':"', $expp3[1]);
	$expp4  = explode('";', $expp33[1]);


	$expp5 = explode('"status";', $result);
	$expp55 = explode(':"', $expp5[1]);
	$expp6  = explode('";', $expp55[1]);


	$expp1  = explode('"proxy";', $result);
	$expp22 = explode(':', $expp1[1]);
	$expp111  = explode(';', $expp22[1]);


	if($expp111[0] != '0'){

		$prox = 'TRUE';

	}else{

		$prox = 'FALSE';

	}

	$resu = array('ISP'=> $expp4[0],'PROXY' => $prox);

	return $resu;

	}

	?>